apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Tag               application-log
        Path              /var/log/app.log
        Multiline         On
        Parser_Firstline  application-log
        Mem_Buf_Limit     5MB
        Refresh_Interval  10

    [INPUT]
        Name              tail
        Tag               access-log
        Path              /var/log/app-access.log
        Parser            access-log
        Mem_Buf_Limit     5MB
        Refresh_Interval  10

    [OUTPUT]
        Name cloudwatch
        Match *
        region ap-south-1
        log_group_name fluent-bit-cloudwatch
        log_stream_prefix from-fluent-bit-
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name   application-log
        Format regex
        Regex XXXXX

    [PARSER]
        Name   access-log
        Format regex
        Regex XXXX

kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: fluentbit
  name: fluentbit-config
