apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "0.5"
          memory: "0.5G"
        limits:
          cpu: "1"
          memory: "1G" 